/**
 * build-icons: every brand asset in `public/` and `docs/brand/`, from the one
 * drawing in `src/assets/corvidPaths.ts`.
 *
 *   npm run brand:icons
 *
 * Writes:
 *
 *   public/favicon.svg             the glyph on the gradient tile, 64 box
 *   public/icon-192.png            the tile at 192
 *   public/icon-512.png            the tile at 512
 *   public/icon-maskable-512.png   full-bleed tile, glyph inside the 80 percent
 *                                  safe zone that a launcher may crop to
 *   public/apple-touch-icon.png    the tile at 180 with square corners, iOS
 *                                  rounds it
 *   public/og-image.png            1200 by 630 link preview: the tile, the
 *                                  name and one line of the description
 *   docs/brand/corvid-mark.png     the full mark at 512 on transparent, for
 *                                  the README
 *   docs/brand/corvid-poses.svg    the model sheet: the bird in every pose,
 *   docs/brand/corvid-poses.png    drawn by its rig (see `poseSheet.ts`)
 *
 * Every colour here is a literal. A favicon cannot read CSS tokens, and
 * librsvg, which sharp rasterises through, does not resolve `var()` either.
 * The values are the light palette's, copied from `src/index.css` through
 * `BRAND` and `TILE`.
 *
 * The outputs are committed. `tests/unit/brand.icons.test.ts` renders the
 * favicon again and compares it with the committed file, so a change to the
 * paths without a rebuild fails CI. `renderFaviconSvg` is exported for that.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import sharp from "sharp";
import {
  BRAND,
  CORVID_BOX,
  CORVID_EYE,
  CORVID_PART_ORDER,
  CORVID_PATHS,
  GLYPH_EYE_R,
  GLYPH_PARTS,
  GLYPH_STROKE,
  MARK_STROKE,
  TILE,
  fitGlyph,
} from "../../src/assets/corvidPaths.ts";
import { renderPoseSheet } from "./poseSheet.ts";

const ROOT = path.resolve(
  path.dirname(fileURLToPath(import.meta.url)),
  "../..",
);
const PUBLIC = path.join(ROOT, "public");
const BRAND_DIR = path.join(ROOT, "docs", "brand");
const FONTS = path.join(PUBLIC, "fonts");

/** The light palette, for the link preview. */
const OG = {
  width: 1200,
  height: 630,
  surface: "#f5f6f9",
  onSurface: "#2a3437",
  onSurfaceVariant: "#566164",
} as const;

/** Safe zone of a maskable icon: a launcher may crop to the central 80 percent. */
const MASKABLE_INSET = 0.19;

// ---------------------------------------------------------------------------
// SVG builders
// ---------------------------------------------------------------------------

/** The glyph paths and the eye, at the tile's placement, as SVG lines. */
function glyphMarkup(box: number, inset: number, indent: string): string {
  const { scale, tx, ty } = fitGlyph(box, inset);
  const lines = [
    `${indent}<g transform="translate(${tx} ${ty}) scale(${scale})" fill="none" stroke="${TILE.ink}" stroke-width="${GLYPH_STROKE}" stroke-linecap="round" stroke-linejoin="round">`,
    ...GLYPH_PARTS.map(
      (part) => `${indent}  <path d="${CORVID_PATHS[part]}" />`,
    ),
    `${indent}  <circle cx="${CORVID_EYE.cx}" cy="${CORVID_EYE.cy}" r="${GLYPH_EYE_R}" fill="${TILE.eye}" stroke="none" />`,
    `${indent}</g>`,
  ];
  return lines.join("\n");
}

/**
 * The tile with the glyph on it. `size` sets the pixel size for a raster
 * render and is left out of the favicon, which scales to the tab strip.
 */
function tileSvg({
  size,
  radius,
  inset,
  comment,
}: {
  size?: number;
  radius: number;
  inset: number;
  comment?: string;
}): string {
  const box = TILE.box;
  const dims = size ? ` width="${size}" height="${size}"` : "";
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${box} ${box}"${dims} role="img" aria-label="Contrack">`,
    `  <title>Contrack</title>`,
    ...(comment ? [comment] : []),
    `  <defs>`,
    `    <linearGradient id="contrack-tile" x1="0" y1="0" x2="1" y2="1">`,
    `      <stop offset="0" stop-color="${TILE.gradientFrom}" />`,
    `      <stop offset="1" stop-color="${TILE.gradientTo}" />`,
    `    </linearGradient>`,
    `  </defs>`,
    `  <rect width="${box}" height="${box}" rx="${radius}" fill="url(#contrack-tile)" />`,
    glyphMarkup(box, inset, "  "),
    `</svg>`,
    ``,
  ].join("\n");
}

const FAVICON_COMMENT = `  <!--
    The Contrack mark: the corvid glyph on the signature gradient tile.

    Generated by scripts/brand/build-icons.ts from src/assets/corvidPaths.ts.
    Do not edit this file. Change the paths, run \`npm run brand:icons\`, and
    commit what it writes: tests/unit/brand.icons.test.ts compares this file
    with the script's output.

    The glyph is the crown, the beak and the wing of the full mark at a
    heavier stroke, placed so its ink keeps ${TILE.glyphInset} units from the tile's edge.
    Literal colours throughout: a favicon cannot read CSS tokens.
  -->`;

/** `public/favicon.svg`, byte for byte. */
export function renderFaviconSvg(): string {
  return tileSvg({
    radius: TILE.radius,
    inset: TILE.glyphInset,
    comment: FAVICON_COMMENT,
  });
}

/** The full mark on nothing, for the README picture. */
function markSvg(size: number, ink: string, eye: string): string {
  return [
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${CORVID_BOX} ${CORVID_BOX}" width="${size}" height="${size}">`,
    `  <g fill="none" stroke="${ink}" stroke-width="${MARK_STROKE}" stroke-linecap="round" stroke-linejoin="round">`,
    ...CORVID_PART_ORDER.map(
      (part) => `    <path d="${CORVID_PATHS[part]}" />`,
    ),
    `  </g>`,
    `  <circle cx="${CORVID_EYE.cx}" cy="${CORVID_EYE.cy}" r="${CORVID_EYE.r}" fill="${eye}" />`,
    `</svg>`,
    ``,
  ].join("\n");
}

// ---------------------------------------------------------------------------
// Raster
// ---------------------------------------------------------------------------

function png(svg: string): Promise<Buffer> {
  return sharp(Buffer.from(svg), { density: 72 })
    .png({ compressionLevel: 9 })
    .toBuffer();
}

/**
 * The first sentence of the site description in `index.html`, after the
 * "Contrack" lead-in, so the preview and the meta tag say the same thing.
 */
export function descriptionLine(indexHtml: string): string {
  const meta = indexHtml.match(/name="description"\s+content="([^"]+)"/);
  if (!meta) throw new Error("index.html has no description meta");
  const body = meta[1]!
    .split(/\s[—-]\s/)
    .pop()!
    .trim();
  const sentence = body.match(/^(.*?\.)(\s|$)/);
  return sentence ? sentence[1]! : body;
}

/** One line of text as a transparent PNG, set in a bundled face. */
function text(
  content: string,
  font: string,
  fontfile: string,
  colour: string,
  width?: number,
): Promise<Buffer> {
  const escaped = content
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;");
  return sharp({
    text: {
      text: `<span foreground="${colour}">${escaped}</span>`,
      font,
      fontfile,
      rgba: true,
      dpi: 72,
      ...(width ? { width } : {}),
    },
  })
    .png()
    .toBuffer();
}

/** The link preview: the tile at left, the name and one line at right. */
async function ogImage(): Promise<Buffer> {
  const indexHtml = await readFile(path.join(ROOT, "index.html"), "utf8");
  const line = descriptionLine(indexHtml);

  const tileSize = 300;
  const tile = await png(
    tileSvg({ size: tileSize, radius: TILE.radius, inset: TILE.glyphInset }),
  );
  const name = await text(
    "Contrack",
    "Manrope ExtraBold 128",
    path.join(FONTS, "manrope-latin.woff2"),
    OG.onSurface,
  );
  const tagline = await text(
    line,
    "Inter 32",
    path.join(FONTS, "inter-latin.woff2"),
    OG.onSurfaceVariant,
    620,
  );
  const nameMeta = await sharp(name).metadata();
  const taglineMeta = await sharp(tagline).metadata();

  const gap = 20;
  const textLeft = 500;
  const blockHeight = nameMeta.height + gap + taglineMeta.height;
  const blockTop = Math.round((OG.height - blockHeight) / 2);

  return sharp({
    create: {
      width: OG.width,
      height: OG.height,
      channels: 4,
      background: OG.surface,
    },
  })
    .composite([
      { input: tile, left: 120, top: Math.round((OG.height - tileSize) / 2) },
      { input: name, left: textLeft, top: blockTop },
      {
        input: tagline,
        left: textLeft + 6,
        top: blockTop + nameMeta.height + gap,
      },
    ])
    .png({ compressionLevel: 9 })
    .toBuffer();
}

// ---------------------------------------------------------------------------
// Build
// ---------------------------------------------------------------------------

export async function build(): Promise<string[]> {
  await mkdir(BRAND_DIR, { recursive: true });
  const tile = (size: number) =>
    png(tileSvg({ size, radius: TILE.radius, inset: TILE.glyphInset }));

  const outputs: Array<[string, Buffer | string]> = [
    [path.join(PUBLIC, "favicon.svg"), renderFaviconSvg()],
    [path.join(PUBLIC, "icon-192.png"), await tile(192)],
    [path.join(PUBLIC, "icon-512.png"), await tile(512)],
    [
      path.join(PUBLIC, "icon-maskable-512.png"),
      await png(
        tileSvg({
          size: 512,
          radius: 0,
          inset: TILE.box * MASKABLE_INSET,
        }),
      ),
    ],
    [
      path.join(PUBLIC, "apple-touch-icon.png"),
      await png(tileSvg({ size: 180, radius: 0, inset: TILE.glyphInset })),
    ],
    [path.join(PUBLIC, "og-image.png"), await ogImage()],
    [
      path.join(BRAND_DIR, "corvid-mark.png"),
      await png(markSvg(512, BRAND.mark, BRAND.eyeLight)),
    ],
    [path.join(BRAND_DIR, "corvid-poses.svg"), renderPoseSheet()],
    [
      path.join(BRAND_DIR, "corvid-poses.png"),
      await sharp(Buffer.from(renderPoseSheet()), { density: 144 })
        .png({ compressionLevel: 9 })
        .toBuffer(),
    ],
  ];

  for (const [file, content] of outputs) {
    await writeFile(file, content);
  }
  return outputs.map(([file]) => path.relative(ROOT, file));
}

const invokedDirectly =
  process.argv[1] !== undefined &&
  import.meta.url === pathToFileURL(path.resolve(process.argv[1])).href;

if (invokedDirectly) {
  const written = await build();
  for (const file of written) console.log(`wrote ${file}`);
}
