// Given names that nearly everyone who carries them shares a gender. The table
// beside this file, `givenNames.tsv.gz`, is generated by
// `scripts/build-given-names.ts` from the World Gender Name Dictionary 2.0
// (WIPO, CC0 1.0): lines of `name<TAB>F` or `name<TAB>M`, sorted by UTF-16 code
// unit, each name folded by `foldName` below.
//
// Most names have no line, on purpose: a name gets one only when at least nine
// in ten of its bearers, across the reporting countries, share a gender.
// Jordan, Taylor, Kim, Jean, Andrea in Italy, Sikh names such as Harpreet and
// most romanized Chinese given names do not, and get a neutral face. The text
// stays one string with an index of line starts, not a Map of 160,000 entries:
// about 2 MB instead of 15 MB, and a lookup is a binary search of about 18
// steps.

import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";

/** Letters that Unicode does not decompose into a base letter and a mark. */
const LETTER_FOLDS: Record<string, string> = {
  ø: "o",
  æ: "ae",
  œ: "oe",
  ß: "ss",
  ł: "l",
  đ: "d",
  ð: "d",
  þ: "th",
  ı: "i",
};

/**
 * The key a name is stored and looked up under. Accents and case go, so "José",
 * "JOSE" and "jose" meet on one line; the Spanish and US records spell it
 * without the accent, and the accented spelling alone is mostly Belgian
 * "Marie-José". Hangul survives, because NFC rejoins the syllables NFD split
 * into jamo.
 */
export function foldName(name: string): string {
  return name
    .normalize("NFD")
    .replace(/\p{M}+/gu, "")
    .toLowerCase()
    .replace(/[øæœßłđðþı]/g, (c) => LETTER_FOLDS[c] ?? c)
    .normalize("NFC");
}

export type GivenNameGender = "female" | "male";

interface Table {
  text: string;
  /** Offset of each line's first character in `text`. */
  starts: Int32Array;
}

let table: Table | null = null;

function load(): Table {
  if (table) return table;
  const text = gunzipSync(
    readFileSync(new URL("./givenNames.tsv.gz", import.meta.url)),
  ).toString("utf8");

  let lines = 0;
  for (let i = 0; i < text.length; i++) if (text.charCodeAt(i) === 10) lines++;
  const starts = new Int32Array(lines);
  let line = 0;
  let start = 0;
  for (let i = 0; i < text.length; i++) {
    if (text.charCodeAt(i) !== 10) continue;
    starts[line++] = start;
    start = i + 1;
  }

  table = { text, starts };
  return table;
}

/**
 * The gender nearly everyone called `name` shares, or null when the table
 * has no line for it. Null covers both names the data calls ambiguous and
 * names it does not know, and the caller treats the two the same way.
 */
export function lookupGivenName(name: string): GivenNameGender | null {
  const key = foldName(name.trim());
  if (!key) return null;

  const { text, starts } = load();
  let lo = 0;
  let hi = starts.length - 1;
  while (lo <= hi) {
    const mid = (lo + hi) >>> 1;
    const start = starts[mid];
    const tab = text.indexOf("\t", start);
    const candidate = text.slice(start, tab);
    if (candidate === key) return text[tab + 1] === "F" ? "female" : "male";
    if (candidate < key) lo = mid + 1;
    else hi = mid - 1;
  }
  return null;
}
