/**
 * Names for the countries that faker has no Latin-script locale for: its
 * Japanese, Korean, Hebrew and Greek data are in their own scripts, and it
 * has nothing for Kenya, Singapore, Estonia or Lithuania.
 *
 * The names are common ones, written the way a contact list in Latin letters
 * holds them: given name first. A surname with a female form, in Greek and in
 * Lithuanian, is listed as both forms.
 *
 * @module scripts/bench/names
 */
import type { Dice } from "./plan.ts";

/** One naming tradition of a country. */
export interface NameGroup {
  /** The tradition's share of the country's people, as a weight. */
  weight: number;
  female: readonly string[];
  male: readonly string[];
  /** Each surname, or its male and female forms. */
  surnames: readonly (string | readonly [male: string, female: string])[];
}

const one = (group: Omit<NameGroup, "weight">): NameGroup[] => [
  { weight: 1, ...group },
];

/** Keyed by a code of `COUNTRIES`. */
export const LOCAL_NAMES: Partial<Record<string, NameGroup[]>> = {
  JP: one({
    female: [
      "Yui",
      "Hina",
      "Aoi",
      "Sakura",
      "Yuna",
      "Mei",
      "Rin",
      "Haruka",
      "Misaki",
      "Nanami",
      "Ayaka",
      "Emi",
      "Kaori",
      "Yuko",
      "Akiko",
      "Naoko",
    ],
    male: [
      "Haruto",
      "Sota",
      "Yuto",
      "Riku",
      "Takumi",
      "Kenta",
      "Daiki",
      "Shota",
      "Ren",
      "Hiroshi",
      "Takashi",
      "Kenji",
      "Yusuke",
      "Kazuki",
      "Ryo",
      "Daisuke",
    ],
    surnames: [
      "Sato",
      "Suzuki",
      "Takahashi",
      "Tanaka",
      "Watanabe",
      "Ito",
      "Yamamoto",
      "Nakamura",
      "Kobayashi",
      "Kato",
      "Yoshida",
      "Yamada",
      "Sasaki",
      "Yamaguchi",
      "Matsumoto",
      "Inoue",
      "Kimura",
      "Hayashi",
      "Shimizu",
      "Mori",
    ],
  }),
  KR: one({
    female: [
      "Seo-yeon",
      "Ji-woo",
      "Ha-eun",
      "Min-seo",
      "Ji-min",
      "Soo-ah",
      "Ye-jin",
      "Yu-na",
      "Su-bin",
      "Da-eun",
      "Eun-ji",
      "Hye-jin",
      "Min-ji",
      "So-yeon",
      "Ji-hye",
      "Na-yeon",
    ],
    male: [
      "Min-jun",
      "Seo-jun",
      "Do-yun",
      "Ji-ho",
      "Ha-jun",
      "Joon-young",
      "Hyun-woo",
      "Ji-hoon",
      "Sung-min",
      "Dong-hyun",
      "Jae-won",
      "Tae-yang",
      "Woo-jin",
      "Sang-hoon",
      "Jun-ho",
      "Min-ho",
    ],
    surnames: [
      "Kim",
      "Lee",
      "Park",
      "Choi",
      "Jung",
      "Kang",
      "Cho",
      "Yoon",
      "Jang",
      "Lim",
      "Han",
      "Oh",
      "Seo",
      "Shin",
      "Kwon",
      "Hwang",
      "Ahn",
      "Song",
      "Yoo",
      "Hong",
    ],
  }),
  IL: one({
    female: [
      "Noa",
      "Tamar",
      "Maya",
      "Shira",
      "Yael",
      "Michal",
      "Avigail",
      "Talia",
      "Hila",
      "Noga",
      "Adi",
      "Liat",
      "Roni",
      "Dana",
      "Efrat",
      "Orly",
    ],
    male: [
      "Noam",
      "Itai",
      "Yonatan",
      "Omer",
      "Ariel",
      "Eitan",
      "Daniel",
      "Yosef",
      "Amit",
      "Ido",
      "Lior",
      "Guy",
      "Tomer",
      "Uri",
      "Avi",
      "Oren",
    ],
    surnames: [
      "Cohen",
      "Levi",
      "Mizrahi",
      "Peretz",
      "Biton",
      "Dahan",
      "Avraham",
      "Friedman",
      "Azoulay",
      "Katz",
      "Malka",
      "Shapira",
      "Ben-David",
      "Goldberg",
      "Rosenberg",
      "Amar",
      "Ohana",
      "Segal",
      "Weiss",
      "Halevi",
    ],
  }),
  GR: one({
    female: [
      "Maria",
      "Eleni",
      "Katerina",
      "Sofia",
      "Georgia",
      "Dimitra",
      "Ioanna",
      "Vasiliki",
      "Angeliki",
      "Christina",
      "Anastasia",
      "Despina",
      "Fotini",
      "Konstantina",
      "Panagiota",
      "Evangelia",
    ],
    male: [
      "Giorgos",
      "Dimitris",
      "Nikos",
      "Kostas",
      "Giannis",
      "Christos",
      "Panagiotis",
      "Vasilis",
      "Thanasis",
      "Alexandros",
      "Michalis",
      "Stavros",
      "Spyros",
      "Manolis",
      "Petros",
      "Andreas",
    ],
    surnames: [
      ["Papadopoulos", "Papadopoulou"],
      ["Pappas", "Pappa"],
      "Oikonomou",
      "Georgiou",
      ["Nikolaidis", "Nikolaidou"],
      ["Vlachos", "Vlachou"],
      ["Papadakis", "Papadaki"],
      ["Karagiannis", "Karagianni"],
      "Antoniou",
      ["Ioannidis", "Ioannidou"],
      ["Makris", "Makri"],
      "Dimitriou",
      ["Konstantinidis", "Konstantinidou"],
      "Christodoulou",
      "Alexiou",
      "Theodorou",
      ["Mavridis", "Mavridou"],
      "Stavrou",
      ["Petridis", "Petridou"],
      ["Angelopoulos", "Angelopoulou"],
    ],
  }),
  KE: one({
    female: [
      "Faith",
      "Mercy",
      "Grace",
      "Esther",
      "Joy",
      "Ruth",
      "Sharon",
      "Lucy",
      "Wanjiru",
      "Akinyi",
      "Njeri",
      "Chebet",
      "Wambui",
      "Atieno",
      "Nafula",
      "Mwende",
    ],
    male: [
      "Brian",
      "Kevin",
      "Dennis",
      "Collins",
      "Peter",
      "Joseph",
      "Samuel",
      "Felix",
      "Kipchoge",
      "Kiprono",
      "Otieno",
      "Mwangi",
      "Juma",
      "Kibet",
      "Omondi",
      "Kamau",
    ],
    surnames: [
      "Otieno",
      "Kamau",
      "Mwangi",
      "Odhiambo",
      "Wanjiku",
      "Kiprono",
      "Ochieng",
      "Njoroge",
      "Mutua",
      "Wekesa",
      "Kipkemboi",
      "Chege",
      "Onyango",
      "Kimani",
      "Owino",
      "Maina",
      "Karanja",
      "Barasa",
      "Cheruiyot",
      "Muthoni",
    ],
  }),
  // Singaporeans of Chinese, Malay and Indian descent, about 74, 14 and 9 in
  // 100. A Malay name has no surname, so the father's name stands in for one.
  SG: [
    {
      weight: 74,
      female: [
        "Wei Ling",
        "Hui Min",
        "Xin Yi",
        "Jia Hui",
        "Mei Ling",
        "Shu Fen",
        "Li Ting",
        "Pei Shan",
        "Rachel",
        "Michelle",
        "Cheryl",
        "Grace",
      ],
      male: [
        "Wei Jie",
        "Jun Hao",
        "Zhi Hao",
        "Kai Wen",
        "Jian Ming",
        "Wei Ming",
        "Guo Liang",
        "Yong Sheng",
        "Daniel",
        "Ryan",
        "Marcus",
        "Jonathan",
      ],
      surnames: [
        "Tan",
        "Lim",
        "Lee",
        "Ng",
        "Ong",
        "Wong",
        "Goh",
        "Chua",
        "Chan",
        "Koh",
        "Teo",
        "Ang",
        "Yeo",
        "Tay",
        "Ho",
        "Low",
      ],
    },
    {
      weight: 14,
      female: ["Siti", "Nur Aisyah", "Farah", "Nurul", "Aishah", "Hidayah"],
      male: ["Muhammad Hafiz", "Ahmad", "Firdaus", "Irfan", "Hakim", "Syafiq"],
      surnames: ["Rahman", "Ismail", "Hassan", "Osman", "Yusof", "Salleh"],
    },
    {
      weight: 9,
      female: ["Priya", "Divya", "Kavitha", "Lakshmi", "Meena", "Anjali"],
      male: ["Arjun", "Ravi", "Suresh", "Vikram", "Rajesh", "Karthik"],
      surnames: ["Pillai", "Nair", "Kumar", "Raj", "Menon", "Krishnan"],
    },
  ],
  EE: one({
    female: [
      "Mari",
      "Kati",
      "Liis",
      "Triin",
      "Kadri",
      "Maarja",
      "Anu",
      "Kristiina",
      "Laura",
      "Sofia",
      "Eliise",
      "Hanna",
      "Grete",
      "Kerli",
      "Piret",
      "Helen",
    ],
    male: [
      "Andres",
      "Jaan",
      "Mart",
      "Toomas",
      "Rasmus",
      "Markus",
      "Martin",
      "Kristjan",
      "Oliver",
      "Robin",
      "Siim",
      "Priit",
      "Tõnu",
      "Rein",
      "Indrek",
      "Kaspar",
    ],
    surnames: [
      "Tamm",
      "Saar",
      "Sepp",
      "Mägi",
      "Kask",
      "Kukk",
      "Rebane",
      "Ilves",
      "Pärn",
      "Koppel",
      "Lepik",
      "Kuusk",
      "Karu",
      "Lill",
      "Teder",
      "Vaher",
      "Laur",
      "Raudsepp",
      "Kallas",
      "Oja",
    ],
  }),
  LT: one({
    female: [
      "Emilija",
      "Gabija",
      "Ugnė",
      "Austėja",
      "Kamilė",
      "Rūta",
      "Eglė",
      "Ieva",
      "Laura",
      "Greta",
      "Jurgita",
      "Aistė",
      "Dalia",
      "Inga",
      "Vaida",
      "Milda",
    ],
    male: [
      "Lukas",
      "Matas",
      "Jonas",
      "Dominykas",
      "Nojus",
      "Mantas",
      "Tomas",
      "Darius",
      "Andrius",
      "Paulius",
      "Mindaugas",
      "Justinas",
      "Vytautas",
      "Karolis",
      "Rokas",
      "Ignas",
    ],
    // The female form a married woman takes.
    surnames: [
      ["Kazlauskas", "Kazlauskienė"],
      ["Jankauskas", "Jankauskienė"],
      ["Petrauskas", "Petrauskienė"],
      ["Stankevičius", "Stankevičienė"],
      ["Vasiliauskas", "Vasiliauskienė"],
      ["Žukauskas", "Žukauskienė"],
      ["Butkus", "Butkienė"],
      ["Paulauskas", "Paulauskienė"],
      ["Urbonas", "Urbonienė"],
      ["Kavaliauskas", "Kavaliauskienė"],
      ["Baranauskas", "Baranauskienė"],
      ["Navickas", "Navickienė"],
      ["Ramanauskas", "Ramanauskienė"],
      ["Savickas", "Savickienė"],
      ["Rimkus", "Rimkienė"],
      ["Žilinskas", "Žilinskienė"],
      ["Sakalauskas", "Sakalauskienė"],
      ["Lukoševičius", "Lukoševičienė"],
      ["Adomaitis", "Adomaitienė"],
      ["Kairys", "Kairienė"],
    ],
  }),
};

/** A name from a country's own traditions, drawn with `d`. */
export function localName(
  groups: readonly NameGroup[],
  d: Dice,
): { firstName: string; lastName: string } {
  const group = d.weighted(groups.map((g) => [g, g.weight] as const));
  const female = d.chance(0.5);
  const surname = d.pick(group.surnames);
  return {
    firstName: d.pick(female ? group.female : group.male),
    lastName: typeof surname === "string" ? surname : surname[female ? 1 : 0],
  };
}
