/**
 * Who is signed in, and the two places that says so.
 *
 * Before 2.0 the app had one user and never had to name them. Now it can have
 * several, and the single most useful thing the chrome can tell someone is
 * which account they are looking at — because the answer decides whose
 * contacts are on the screen. Getting that wrong is not a cosmetic mistake.
 *
 * Two placements, one component set. The sidebar is `hidden md:flex`, so on a
 * phone it renders nothing at all; the same identity therefore appears at the
 * top of Settings, which is the one destination every screen size shares.
 *
 * Everything here hides when `authRequired` is false. On an un-gated instance
 * the principal is a local owner nobody signs in as, so an avatar, a name and
 * a "Sign out" that cannot sign anyone out would all be fiction.
 */
import React, { useCallback, useRef, useState } from "react";
import { Link } from "react-router-dom";
import { LogOut, ShieldCheck, UserRound } from "lucide-react";
import { useDismissable } from "../../hooks/useDismissable";
import { Badge } from "../ui/Badge";
import { accountAvatarUrl } from "../../lib/avatar";
import { cn } from "../../lib/utils";
import { useAuth } from "./AuthGate";
import type { AccountUser } from "../../api/auth";
import { usePreferences } from "../../contexts/PreferencesContext";

/**
 * The account's role, as a pill.
 *
 * Only "admin" is drawn in the primary tint. A member badge in the same
 * colour would give equal weight to the ordinary case, and the whole point of
 * the badge is that one of the two is worth noticing.
 */
export const RoleBadge = ({
  role,
  className,
}: {
  role: string;
  className?: string;
}) =>
  role === "admin" ? (
    <Badge
      tone="primary"
      icon={<ShieldCheck className="w-3 h-3" />}
      className={className}
    >
      Admin
    </Badge>
  ) : (
    <Badge className={className}>Member</Badge>
  );

/** The account's mark. Deterministic initials, generated by this server. */
export const AccountAvatar = ({
  user,
  size = 32,
  className,
}: {
  user: Pick<AccountUser, "username" | "displayName">;
  size?: number;
  className?: string;
}) => {
  // The monogram is a served image, so it cannot inherit the page's palette.
  // It answers `prefers-color-scheme` on its own, which covers the default
  // `system` theme; a theme chosen explicitly has to travel in the URL.
  const { preferences, mode } = usePreferences();
  const theme = preferences.theme === "system" ? undefined : mode;
  return (
    <img
      src={accountAvatarUrl(user.username, theme)}
      alt=""
      width={size}
      height={size}
      // Decorative: every place this appears also carries the name in text or
      // in an accessible label, and a screen reader announcing the same account
      // twice is noise.
      aria-hidden="true"
      className={cn(
        "rounded-full bg-surface-container-high shrink-0",
        className,
      )}
      style={{ width: size, height: size }}
    />
  );
};

/** The name to show, falling back through what the account actually has. */
export function accountLabel(user: AccountUser): string {
  return user.displayName?.trim() || user.username;
}

// ---------------------------------------------------------------------------
// Desktop: the sidebar avatar and its menu
// ---------------------------------------------------------------------------

const MENU_ITEM = cn(
  "flex items-center gap-2.5 w-full px-3 py-2.5 rounded-xl text-sm text-left",
  "text-on-surface hover:bg-primary/10 hover:text-primary transition-colors",
);

/**
 * The signed-in account at the foot of the sidebar.
 *
 * Renders nothing on an un-gated instance and nothing before `/status` has
 * answered, rather than a placeholder: the sidebar is 64 px of icons and a
 * grey circle that turns into a face is worse than a gap that fills.
 */
export const SidebarIdentity = () => {
  const { user, authRequired, isAdmin, instanceName, signOut } = useAuth();
  const [open, setOpen] = useState(false);
  const trigger = useRef<HTMLButtonElement>(null);
  // Closing puts focus back on the avatar. Without it, dismissing with Escape
  // unmounts the focused element and the browser resets to <body>, so the
  // next Tab restarts from the top of the document — the keyboard user's
  // place in the page is destroyed by the act of closing a menu.
  const close = useCallback(() => {
    setOpen(false);
    trigger.current?.focus({ preventScroll: true });
  }, []);
  const ref = useDismissable<HTMLDivElement>(open, close);

  if (!authRequired || !user) return null;
  const label = accountLabel(user);

  return (
    <div ref={ref} className="relative flex justify-center w-full">
      <button
        ref={trigger}
        type="button"
        onClick={() => setOpen((v) => !v)}
        aria-expanded={open}
        aria-label={`Signed in as ${label}. Account menu.`}
        className={cn(
          "inline-flex items-center justify-center min-w-[44px] min-h-[44px] rounded-full",
          "transition-colors outline-none focus-visible:ring-2 focus-visible:ring-primary",
          open ? "bg-primary/15" : "hover:bg-surface-container-high",
        )}
      >
        <AccountAvatar
          user={user}
          size={32}
          className={cn(open && "ring-2 ring-primary")}
        />
      </button>

      {/*
          A disclosure, not a menu. `role="menu"` promises arrow-key movement,
          Home and End, and a roving tabindex, and it also forbids the
          non-menuitem content this panel exists to show — the name, the email
          and the role. Two ordinary controls in a labelled panel are read
          correctly by everything and behave the way Tab already works.
        */}
      {open && (
        <div
          aria-label="Account"
          className={cn(
            "absolute left-full bottom-0 ml-3 z-50 w-60 p-2",
            "glass-panel rounded-2xl shadow-xl",
          )}
        >
          <div className="px-3 py-2">
            {/*
              Which instance, above who. Somebody with an account on two
              Contracks has two identical menus otherwise, and the account
              name is the half that is the same on both.
            */}
            {instanceName && (
              <p className="text-[10px] font-bold uppercase tracking-widest text-primary truncate mb-1">
                {instanceName}
              </p>
            )}
            <p className="font-bold text-sm text-on-surface truncate">
              {label}
            </p>
            <p className="text-xs text-on-surface-variant truncate">
              {user.email}
            </p>
            <RoleBadge role={isAdmin ? "admin" : "member"} className="mt-2" />
          </div>
          <div className="h-px bg-surface-container-high my-1" />
          <Link
            to="/settings/account"
            onClick={() => setOpen(false)}
            className={MENU_ITEM}
          >
            <UserRound className="w-4 h-4" />
            Account settings
          </Link>
          <button
            type="button"
            onClick={() => {
              setOpen(false);
              void signOut();
            }}
            className={cn(MENU_ITEM, "text-error hover:bg-error/10")}
          >
            <LogOut className="w-4 h-4" />
            Sign out
          </button>
        </div>
      )}
    </div>
  );
};

// ---------------------------------------------------------------------------
// Mobile: the row at the top of Settings
// ---------------------------------------------------------------------------

/**
 * The same identity, for the screen sizes the sidebar does not reach.
 *
 * `md:hidden` mirrors the sidebar's `hidden md:flex` exactly, so the account
 * is named once at every width and never twice.
 */
export const SettingsIdentityRow = () => {
  const { user, authRequired, isAdmin, signOut } = useAuth();
  if (!authRequired || !user) return null;
  const label = accountLabel(user);

  return (
    <section className="md:hidden">
      <div
        className={cn(
          "bg-surface-container-lowest rounded-2xl shadow-sm",
          "flex items-center gap-3 p-3",
        )}
      >
        <Link
          to="/settings/account"
          className="flex items-center gap-3 flex-1 min-w-0 rounded-xl py-1 -my-1"
        >
          <AccountAvatar user={user} size={40} />
          <span className="flex-1 min-w-0">
            <span className="flex items-center gap-2 min-w-0">
              <span className="font-bold text-sm text-on-surface truncate">
                {label}
              </span>
              <RoleBadge role={isAdmin ? "admin" : "member"} />
            </span>
            <span className="block text-xs text-on-surface-variant truncate">
              {user.email}
            </span>
          </span>
        </Link>
        <button
          type="button"
          onClick={() => void signOut()}
          aria-label="Sign out"
          className={cn(
            "shrink-0 inline-flex items-center justify-center",
            "min-w-[44px] min-h-[44px] rounded-full",
            "text-on-surface-variant hover:text-error hover:bg-error/10 transition-colors",
          )}
        >
          <LogOut className="w-5 h-5" />
        </button>
      </div>
    </section>
  );
};
